### ISSUE TITLE
Добавить логгирование на backend

### ISSUE THREAD

**Issue by FEgor04** [FEgor04/itmo-is-1#96]
Сейчас на бэкенде практически нет логгирования.
Необходимо настроить формат логирования и дописать его для всех ручек.
Для того, чтобы избавиться от дублирования кода, думаю можно использовать Spring AOP

#### GET /vehicles
Для нее лог должен содержать следующие записи:
- INFO: handling request to GET /vehicles, page = ..., pageSize = .., etc., request UUID: XXX
- INFO: fetched vehicles from database. data.length: X, totalEntries: Y, request UUID: XXX
- INFO: finished handling request to /GET vehicles, request UUID: XXX

#### PUT /vehicles/{id}
- INFO: handling request to PUT /vehicles/123, ...
- DEBUG: check user X authorities to modify vehicle #123
- INFO: user is allowed to modify vehicle
- INFO: updated vehicle #123

**Comment by forafox** [comment]
Интрументы логгирования реализованы. Необходимо сообща решить, где, что и как логгировать (куда добавлять аннотации).
